locals {
  all_names = reverse(sort([
    for name in data.aws_instance.each : name.tags.Name
  ]))
  size = length(local.all_names)
  _latest = local.size == 0 ? "0" : tonumber(
    trimprefix(
      element(local.all_names, local.size),
      join("", [
        local.os_prefix[var.os],
        local.region_code[local.region],
        local.apms_id_short,
        local.env_id_char,
      ])
    )
  )
  latest = local._latest + var.user_preferred_index
}

data "aws_ssm_parameter" "ami_id" {
  name = local.ami_location
}

data "aws_caller_identity" "current" {}

data "aws_region" "current" {}

data "aws_subnet" "vpc_identifier" {
  id = data.aws_subnets.subnets.ids[0]
}

data "aws_subnets" "subnet_az_id" {
  count = var.subnet_az_id != "" ? 1 : 0
  tags = {
    Name = join("-", [
      local.subnet_identifier,
      var.subnet_az_id
    ])
  }
}

data "aws_subnets" "subnets" {
  tags = {
    Name = (var.subnet_name == ""
      ? join("-", [
        local.subnet_identifier,
        "az*"
      ])
      : var.subnet_name
    )
  }
}

data "aws_kms_alias" "ebs_key" {
  name = "alias/TEC-EBS"
}

data "aws_security_groups" "FM_securitygroup" {
  filter {
    name = "group-name"
    values = [join("-", [
      local.FMManagedSecurityGroup[local.region],
      data.aws_subnet.vpc_identifier.vpc_id
    ])]
  }
}

data "aws_instances" "all_matching" {
  filter {
    name = "tag:Name"
    values = [
      join("", [
        local.os_prefix[var.os],
        local.region_code[local.region],
        local.apms_id_short,
        local.env_id_char,
        "*"
      ])
    ]
  }
}

data "aws_instance" "each" {
  for_each    = toset([for name in data.aws_instances.all_matching.ids : name])
  instance_id = each.value
}

resource "aws_key_pair" "ssh_key" {
  count = var.create_ssh_key_pair == true ? 1 : 0
  key_name = join("-", [
    local.tec_account,
    local.environment,
    local.apms_id_short
  ])
  public_key = var.public_key
}

resource "aws_instance" "ec2-instance" {
  count = var.number_of_instances

  ami           = var.ami_id != "" ? var.ami_id : data.aws_ssm_parameter.ami_id.value
  instance_type = var.instance_type

  subnet_id = (
    var.subnet_az_id != "" ?
    data.aws_subnets.subnet_az_id[0].ids[0] :
    data.aws_subnets.subnets.ids[count.index % length(data.aws_subnets.subnets.ids)]
  )

  tags = merge(
    local.shared_tags, {
      Name = var.instance_name != "" ? var.instance_name : join("", [
        local.os_prefix[var.os],
        local.region_code[local.region],
        local.apms_id_short,
        local.env_id_char,
        format("%03d", local.latest + count.index + 1)
      ])
  })

  vpc_security_group_ids = concat(
    var.security_groups,
    data.aws_security_groups.FM_securitygroup.ids
  )

  iam_instance_profile    = var.iam_instance_profile
  disable_api_termination = true

  user_data_base64 = base64encode(var.user_data)
  key_name         = one(aws_key_pair.ssh_key[*].key_name)

  root_block_device {
    encrypted = true
    tags = merge(
      local.shared_tags, {
        Name = var.instance_name != "" ? var.instance_name : join("", [
          local.os_prefix[var.os],
          local.region_code[local.region],
          local.apms_id_short,
          local.env_id_char,
          format("%03d", local.latest + count.index + 1),
          "-root"
        ])
      }
    )
    volume_type = "gp3"
    volume_size = var.root_volume_size
    kms_key_id  = data.aws_kms_alias.ebs_key.target_key_arn
  }

  lifecycle {
    create_before_destroy = true

    ignore_changes = [
      # Ignore as name suffix is autogenerated to match instance
      root_block_device[0].tags["Name"],
      # Ignore as name suffix is autogenerated to match instance
      tags["Name"]
    ]

    precondition {
      condition = var.instance_name == "" || (
        can(regex("^[[:alnum:]-]+$", var.instance_name)) // Only RFC1034 alphanumeric or - chars
      )
      error_message = "instance_name (${var.instance_name}) contains invalid characters"
    }

    precondition {
      condition = var.instance_name == "" || (
        (
          can(regex("^Windows.*", var.os))   // In the case of Windows
          && length(var.instance_name) >= 5  //  Min length of 5
          && length(var.instance_name) <= 15 //  NetBIOS protocol requirement of non-FQDN hostname
        )
        || (
          !can(regex("^Windows.*", var.os))  // In the case of Non-Windows/Linux
          && length(var.instance_name) >= 5  //  Min length of 5
          && length(var.instance_name) <= 63 //  RFC1034#3.1 requirement of first name label minus .
        )
      )
      error_message = "instance_name (${var.instance_name}) does not conform to hostname length constraints"
    }
  }
}

resource "aws_ebs_volume" "additional_ebs_volumes" {
  count = var.number_of_instances * length(var.additional_ebs_config)

  availability_zone = element(
    aws_instance.ec2-instance[*].availability_zone,
    floor(count.index / length(var.additional_ebs_config))
  )

  size = (
    var.additional_ebs_config[
      count.index %
      length(var.additional_ebs_config)
    ].additional_ebs_volume_size
  )

  kms_key_id = data.aws_kms_alias.ebs_key.target_key_arn
  encrypted  = true

  type = (
    var.additional_ebs_config[
      count.index %
      length(var.additional_ebs_config)
    ].additional_ebs_type
  )

  iops = (
    var.additional_ebs_config[
      count.index %
      length(var.additional_ebs_config)
    ].additional_ebs_iops
  )

  tags = merge(
    local.shared_tags, {
      Name = (var.instance_name != ""
        ? join("-", [
          var.instance_name,
          "-",
          format("%03d", count.index + 1)
        ])
        : join("", [
          local.region_code[local.region],
          local.apms_id_short,
          local.env_id_char,
          local.os_prefix[var.os],
          format("%03d",
            local.latest +
            count.index %
            length(var.additional_ebs_config) + 1
          ),
          "-",
          upper(
            var.additional_ebs_config[
              count.index %
              length(var.additional_ebs_config)
            ].additional_ebs_mount_point
          )
      ]))
    }
  )

  lifecycle {
    ignore_changes        = [tags["Name"]] # Ignore as name suffix is autogenerated to match instance
    create_before_destroy = true
  }
}

resource "aws_volume_attachment" "additional_ebs_volumes" {
  count = var.number_of_instances * length(var.additional_ebs_config)

  volume_id = aws_ebs_volume.additional_ebs_volumes[count.index].id

  device_name = (
    var.additional_ebs_config[
      count.index %
      length(var.additional_ebs_config)
    ].additional_ebs_device_name
  )

  instance_id = (
    element(
      aws_instance.ec2-instance[*].id,
      floor(count.index / length(var.additional_ebs_config))
    )
  )
}
